# Basic
title: tomsun28
subtitle: 
description: 
# 头像里面的标题
avatarTitle: tomsun28
# 头像里面的描述
avatarDesc: 
url: "https://tom.usthe.com"

# Comment
comment:
    # disqus: 
    # uyan: 2146669  # 有言id,登录有言官网申请
    gitment: tomsun28

# Social
social:
    weibo: tomsun28 
    github: tomsun28
    # twitter: 
    mail: tomsun28@outlook.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 423830c130ac0dbedf4f3623212bf5b1  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章

# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #000000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 6
paginate_path: "page/:num/"

#markdown解析
markdown: kramdown

kramdown:
  input: GFM
